name: porcupine-http
version: 0.0.1.0
synopsis: A tool to express portable, composable and reusable datascience task pipelines
description: See README at <https://github.com/tweag/porcupine#README.md>
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
category: Numerical, JSON
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - containers
  - transformers
  - safe-exceptions
  - http-conduit
  - http-client
  - resourcet
  - bytestring
  - mime-types
  - streaming
  - streaming-bytestring
  - conduit
  - streaming-conduit
  - text
  - reader-soup
  - porcupine-core

library:
  source-dirs: src

executables:
  example-pokeapi:
    source-dirs: examples
    main: ExamplePokeAPI.hs
    dependencies:
      - porcupine-core
      - porcupine-http
      - docrecords
      - aeson
      - unordered-containers
      - text
