name: porcupine-s3
version: 0.1.0.0
synopsis: A location accessor for porcupine to connect to AWS S3 sources/sinks
description: |
  Gives a porcupine task pipeline access to AWS S3 objects (read and write). See
  the README at <https://github.com/tweag/porcupine#README.md> and the examples
  in the `porcupine-s3` package.
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
homepage: https://tweag.github.io/porcupine/
category: Data, Arrows, Combinators, Control, AWS, Cloud
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - mtl
  - safe-exceptions
  - amazonka
  - amazonka-core
  - amazonka-s3
  - katip
  - lens
  - monad-control
  - mmorph
  - resourcet
  - bytestring
  - streaming
  - streaming-bytestring
  - streaming-conduit
  - directory
  - reader-soup == 0.1.*
  - porcupine-core == 0.1.*
  - retry
  - text
  - filepath
  - conduit

library:
  source-dirs: src

executables:
  exampleS3:
    source-dirs: examples
    main: ExampleS3.hs
    dependencies:
      - porcupine-core
      - porcupine-s3
      - docrecords
      - aeson
      - unordered-containers
